FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive
RUN ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
RUN apt update && apt install -y openjdk-8-jdk
RUN apt update && apt install -y python3-pip
RUN apt update && apt install -y vim

