---
  apiVersion: v1
  kind: Pod
  metadata:
    name: spark
    labels:
      app: spark
  spec:
    containers:
      - name: spark
        image: ubuntu:20.04
        command: ["/bin/bash", "-c", "while true; do echo 1; sleep 1; done"]
      - name: kube-proxy-sidecar
        image: bitnami/kubectl
        command: ["kubectl", "proxy"]
        ports:
          - containerPort: 8001
--
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-spark
  labels:
    app: spark
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
--      
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-spark
  labels:
    type: local
    app: spark
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/spark"
