kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-spark
  labels:
    type: local
    app: spark
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/spark"
