kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-spark
  labels:
    app: spark
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi