FROM registry.access.redhat.com/rhscl/s2i-base-rhel7:latest
RUN yum install wget
RUN wget https://wxtoimgrestored.xyz/downloads-src/wxtoimg-linux64-2.10.11-1.tar.gz
RUN tar xvfz wxtoimg-linux64-2.10.11-1.tar.gz

